SAMPLES = [
    (
        "学校",
        "私は毎日学校に行きます。",
        "がっこう",
        "school",
        "I go to school every day.",
        "noun",
    ),
    (
        "猫",
        "猫がベッドで寝ています。",
        "ねこ",
        "cat",
        "The cat is sleeping on the bed.",
        "noun",
    ),
    ("食べる", "朝ご飯を食べる。", "たべる", "eat", "I eat breakfast.", "verb"),
    (
        "勉強",
        "日本語を勉強しています。",
        "べんきょう",
        "study",
        "I am studying Japanese.",
        "verb",
    ),
    (
        "食べる",
        "私は毎日リンゴを一個食べます。",
        "たべる",
        "eat",
        "I eat one apple every day.",
        "verb",
    ),
    (
        "日本語",
        "日本語の勉強はとても楽しいです。",
        "にほんご",
        "Japanesee",
        "Studying Japanese is very fun.",
        "noun",
    ),
    (
        "先生",
        "あの人は私の大学の先生です。",
        "せんせい",
        "teacher",
        "That person is my university teacher.",
        "noun",
    ),
    (
        "行く",
        "明日、友達と一緒に映画館に行きます。",
        "いく",
        "go",
        "I am going to the movie theater with a friend tomorrow.",
        "verb",
    ),
    (
        "読む",
        "寝る前にいつも本を読みます。",
        "よむ",
        "read",
        "I always read a book before going to bed.",
        "verb",
    ),
    (
        "水",
        "冷たい水が飲みたいです。",
        "みず",
        "water",
        "I want to drink cold water.",
        "noun",
    ),
    (
        "友達",
        "週末に友達と公園で遊びました。",
        "ともだち",
        "friend",
        "I played at the park with my friend on the weekend.",
        "noun",
    ),
    (
        "天気",
        "今日はとても良い天気ですね。",
        "てんき",
        "weather",
        "The weather is very nice today, isn't it?",
        "noun",
    ),
    (
        "新しい",
        "先週、新しい靴を買いました。",
        "あたらしい",
        "new",
        "I bought new shoes last week.",
        "adjective",
    ),
    (
        "時間",
        "約束のまで、まだ時間があります。",
        "じかん",
        "time",
        "There is still time until the appointment.",
        "noun",
    ),
    (
        "見る",
        "昨日、面白いテレビ番組を見ました。",
        "みる",
        "watch; see; look",
        "I watched an interesting TV program yesterday.",
        "verb",
    ),
    (
        "会社",
        "父は大きな会社で働いています。",
        "かいしゃ",
        "company",
        "My father works for a large company.",
        "noun",
    ),
]
