# defaults to hiragana unless set to
# "katakana" or "romanji"
translation-kana = "katakana"

# set to the name of the filter that
# you want to use when first opening
# the app
default-filter = "spring26"
